name: iptv
on:
  schedule:
    - cron: '20 0,7 * * *'       
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install selenium requests futures eventlet

      - name: run iptvpy
        run: |
          cd $GITHUB_WORKSPACE
          python ./iptv2.py
          python ./iptv.py
           
      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit *.txt -m "更新直播源"
          #git commit *.m3u -m "Update results"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0  # 使用最新稳定版本
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: iptv
          force: true
