name: 测试酒店ip
on:
#  schedule:
#    - cron: 30 10 */3 * *
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install selenium requests futures eventlet

    - name: run iptvpy
      run: python ${{ github.workspace }}/test_iptv.py
      
    - name: 提交更新
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "更新酒店源ip"
        git push
